### plotly

an open-source, browser-based graphing library used to create interactive, publication-quality data visualizations.

Plotly is a Python library used to create interactive graphs.

Core Modules::

plotly.express (PX): The high-level wrapper. It creates entire, pre-styled charts in a single line of code using Pandas DataFrames.

plotly.graph_objects (GO): The low-level API. It gives you absolute control over individual elements, layouts, and data structures.


In [2]:
pip install plotly

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
from IPython.display import HTML, display

In [4]:
import plotly.express as px

import pandas as pd

df = pd.DataFrame({
    "Order_ID": range(101, 121),
    "Product": [
        "Laptop","Mobile","Tablet","Laptop","Mobile",
        "Tablet","Laptop","Mobile","Tablet","Laptop",
        "Mobile","Tablet","Laptop","Mobile","Tablet",
        "Laptop","Mobile","Tablet","Laptop","Mobile"
    ],
    "Category": [
        "Electronics","Electronics","Electronics","Electronics","Electronics",
        "Electronics","Electronics","Electronics","Electronics","Electronics",
        "Electronics","Electronics","Electronics","Electronics","Electronics",
        "Electronics","Electronics","Electronics","Electronics","Electronics"
    ],
    "City": [
        "Delhi","Mumbai","Lucknow","Delhi","Lucknow",
        "Mumbai","Delhi","Lucknow","Mumbai","Delhi",
        "Lucknow","Mumbai","Delhi","Lucknow","Mumbai",
        "Delhi","Lucknow","Mumbai","Delhi","Lucknow"
    ],
    "Sales": [
        65000,30000,25000,70000,32000,
        27000,68000,35000,26000,72000,
        33000,28000,75000,34000,29000,
        76000,36000,30000,78000,37000
    ],
    "Profit": [
        12000,5000,4500,13000,5500,
        4700,12500,6000,4800,14000,
        6200,5000,14500,6300,5200,
        15000,6500,5400,15500,6800
    ],
    "Quantity": [
        5,10,8,6,9,
        7,5,11,8,6,
        10,7,5,9,8,
        4,12,9,5,10
    ]
})

print(df)



    Order_ID Product     Category     City  Sales  Profit  Quantity
0        101  Laptop  Electronics    Delhi  65000   12000         5
1        102  Mobile  Electronics   Mumbai  30000    5000        10
2        103  Tablet  Electronics  Lucknow  25000    4500         8
3        104  Laptop  Electronics    Delhi  70000   13000         6
4        105  Mobile  Electronics  Lucknow  32000    5500         9
5        106  Tablet  Electronics   Mumbai  27000    4700         7
6        107  Laptop  Electronics    Delhi  68000   12500         5
7        108  Mobile  Electronics  Lucknow  35000    6000        11
8        109  Tablet  Electronics   Mumbai  26000    4800         8
9        110  Laptop  Electronics    Delhi  72000   14000         6
10       111  Mobile  Electronics  Lucknow  33000    6200        10
11       112  Tablet  Electronics   Mumbai  28000    5000         7
12       113  Laptop  Electronics    Delhi  75000   14500         5
13       114  Mobile  Electronics  Lucknow  3400

In [17]:
fig = px.scatter(df,
                 x="Sales",
                 y="Profit",
                 title="Sales vs Profit",
                 color="Category")

# fig.show(renderer="browser")
display(fig)


In [19]:
total_sale = df.groupby("Product")["Sales"].sum().reset_index()

fig = px.bar(total_sale, x="Product", y="Sales",color = 'Product' , title="Total Sales by Product")
# fig.show(renderer="browser")
display(fig)

Plotly Practice Questions

Dataset: Use the given DataFrame.

1. Create a bar chart showing the total Sales for each Product.

2. Create a pie chart showing the Sales distribution by Product.

3. Create a scatter plot between Sales and Profit, using Quantity as the marker size and Product as the color.

4. Create a histogram of Sales with 10 bins.

5. Create a box plot to compare the Sales distribution of each Product.

6. Using groupby('City'), calculate the total Sales of each city and create a bar chart.

7. Using groupby('Product'), calculate the average Profit of each product and create a line chart.


In [20]:
fig = px.pie(total_sale,
             names='Product',
             values='Sales',
             title='Sales Distribution by Product',
             color='Product'
)

# fig.show(renderer="browser")

display(fig)

In [21]:
fig = px.scatter(
    df,
    x='Sales',
    y='Profit',
    size='Quantity',
    color='Product',
    title='Sales vs Profit'
)

# fig.show(renderer="browser")

display(fig)

In [22]:
fig = px.histogram(df, x="Sales", nbins=10, title="Sales Distribution")
# fig.show(renderer="browser")
display(fig)

In [14]:
# sales distribution of each product using box plot 
from IPython.display import HTML, display

fig = px.box(df,
             x='Product',
             y='Sales',
             title='Sales Distribution by Product'
)

display(fig)
# fig.show(renderer="browser")


In [23]:
#6. Using groupby('City'), calculate the total Sales of each city and create a bar chart.

total_sale_city = df.groupby("City")["Sales"].sum().reset_index()   

fig = px.bar(total_sale_city, x="City", y="Sales", color='City', title="Total Sales by City")

display(fig)



In [24]:
avg_prof = df.groupby('Product')['Profit'].mean().reset_index()

fig = px.line(avg_prof, x='Product', y='Profit', title='Average Profit by Product')

display(fig)

In [63]:
# matrix addition
import numpy as np 

a = np.array([[2,4],[5,6]])
b= np.array([[6,7],[7,8]])

print(a+b)

print(a*b) # element wise multiplication

print(a@b) # dot product
print("Multiplication :", np.matmul(a, b))

[[ 8 11]
 [12 14]]
[[12 28]
 [35 48]]
[[40 46]
 [72 83]]
Multiplication : [[40 46]
 [72 83]]


In [46]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A)

print("Transpose of A:")
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [56]:
print("Identity matrix :")
print(np.eye(4))

Identity matrix :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [60]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,4]])

c= a+b

print(np.linalg.inv(a))# inverse of a matrix



print(np.linalg.det(c)) # determinant of b

[[-2.   1. ]
 [ 1.5 -0.5]]
-32.0
