==============================
Practice Questions
 ==============================

 1. Find the shape, size and dimensions of both matrices.

 2. Perform element-wise addition of A and B.

 3. Perform element-wise subtraction (A - B).

 4. Perform element-wise multiplication.

 5. Perform matrix multiplication using np.matmul().

 6. Find the transpose of both matrices.

 7. Find the determinant of matrix A.

 8. Find the inverse of matrix A (if possible).

 9. Find the trace (sum of diagonal elements) of both matrices.

 10. Find the maximum, minimum, mean and sum of matrix A.

 11. Find the row-wise sum and column-wise sum of matrix B.

 12. Extract:
     a) First row
     b) Second column
     c) Last row
     d) Bottom-right element

 13. Reshape matrix A into a (1,9) array and flatten matrix B.

 14. Find the eigenvalues and eigenvectors of matrix A.

 15. Concatenate A and B:
     a) Horizontally (hstack)
     b) Vertically (vstack)

In [1]:
import numpy as np

# Matrix A
A = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

# Matrix B
B = np.array([
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)


Matrix A:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix B:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [9]:
print("Shapes of A and B:", A.shape, B.shape)

print("\n Size of A and B:", A.size, B.size)

print(f"\n Dimensions of A : {A.ndim} , and B : {B.ndim}")

print("\n Addition :" , A+B)

print("\n Substraction :" , A-B)

print("\n Element-wise Multiplication :" , A*B)

print("\n Multiplication :" , np.matmul(A,B))

print(f"Transpose of matrix A: {A.T} , and B : {B.T}")

print(f"Determinant of matrix A: {np.linalg.det(A)} , and B : {np.linalg.det(B)}")




Shapes of A and B: (3, 3) (3, 3)

 Size of A and B: 9 9

 Dimensions of A : 2 , and B : 2

 Addition : [[ 3  7 11]
 [15 19 23]
 [27 31 35]]

 Substraction : [[1 1 1]
 [1 1 1]
 [1 1 1]]

 Element-wise Multiplication : [[  2  12  30]
 [ 56  90 132]
 [182 240 306]]

 Multiplication : [[108 132 156]
 [234 294 354]
 [360 456 552]]
Transpose of matrix A: [[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]] , and B : [[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
Determinant of matrix A: 0.0 , and B : 4.263256414560604e-14


In [7]:
# not possible

# print("Inverse of Matrix A:\n", np.linalg.inv(A))

In [ ]:
print("Trace of matrix A:", np.trace(A))

# print(A.trace())

print("Trace of matrix B:", np.trace(B))
# print(B.trace())

27
30


In [13]:
print("Maximum value in matrix A:", np.max(A))
print("Minimum value in matrix A:", np.min(A))
  
print(f"Sum of matrix A: {A.sum()}, Sum of matrix B: {B.sum()}")

print("Mean of matrix A:", np.mean(A))

Maximum value in matrix A: 18
Minimum value in matrix A: 2
Sum of matrix A: 90, Sum of matrix B: 81
Mean of matrix A: 10.0


In [14]:
print("Row wise sum of matrix B:", np.sum(B, axis=1))
print("Column wise sum of matrix B:", np.sum(B, axis=0))

Row wise sum of matrix B: [ 9 27 45]
Column wise sum of matrix B: [21 27 33]


In [17]:
print("Extract First row of matrix A:", A[0, :])

print("Second column of matrix B:", B[:, 1])

print("Extact last row " , A[-1])

print("Bottom right element :" , A[-1 , -1])




Extract First row of matrix A: [2 4 6]
Second column of matrix B: [ 3  9 15]
Extact last row  [14 16 18]
Bottom right element : 18


In [ ]:
print("Flattened matrix B:", B.flatten())  # flatten matrix means convert 2D array to 1D array

print("Reshape A to 1D array:", A.reshape(1,9))

Flattened matrix B: [ 1  3  5  7  9 11 13 15 17]
Reshape A to 1D array: [[ 2  4  6  8 10 12 14 16 18]]


In [20]:
# find Enginevalue and Eigenvector of a matrix A

print("Eigenvalues and Eigenvectors of matrix A:")

print(np.linalg.eig(A))  # returns a tuple of eigenvalues and eigenvectors


Eigenvalues and Eigenvectors of matrix A:
EigResult(eigenvalues=array([ 3.22336879e+01, -2.23368794e+00, -1.95183697e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [21]:
# 15. Concatenate A and B:
    #  a) Horizontally (hstack)
    #  b) Vertically (vstack)
    
    
print("Horizontally concatenated A and B:\n", np.hstack((A, B)))
print("\nVertically concatenated A and B:\n", np.vstack((A, B)))

Horizontally concatenated A and B:
 [[ 2  4  6  1  3  5]
 [ 8 10 12  7  9 11]
 [14 16 18 13 15 17]]

Vertically concatenated A and B:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
