### NUMPY :
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices. 

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [32]:
import numpy as np

list = [1,2,3,4,5]
arr = np.array(list)
print("Array : " , arr)
print("\n")


arr2 = np.array([[1,2,3] , [4,5,6]])
print("2D arrya: \n\n" , arr2)

arr3 = np.array([[[1,2,3] , [4,5,6]] , [[11,12,13] , [14,15,16]]])
print("3D array: \n\n" , arr3)

print("\n" ,arr2[1,1])
print("\n" , arr3[1 ,0 ,0])

print("Dimention of the array: " , np.ndim(arr3)) # gives the dimension of the array

print("Size gives the number of elements in the array:\n ")

print(arr3.size)
print(arr2.size)
print(arr.size)


print("Shapes of the arrays: \n")

print(arr3.shape)
print(arr2.shape)
print(arr.shape)


print("Slicing of the array: \n")
print(arr[1:3])

print(arr[::-1]) # reverse the array

is_palindrome = np.array_equal(arr , arr[::-1]) 
print("Is the array a palindrome? : " , is_palindrome)




Array :  [1 2 3 4 5]


2D arrya: 

 [[1 2 3]
 [4 5 6]]
3D array: 

 [[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]

 5

 11
Dimention of the array:  3
Size gives the number of elements in the array:
 
12
6
5
Shapes of the arrays: 

(2, 2, 3)
(2, 3)
(5,)
Slicing of the array: 

[2 3]
[5 4 3 2 1]
Is the array a palindrome? :  False


In [ ]:
a = np.array([2,4,6,8] , dtype = float)


print(a)
print(a+2)
print(a*2)
print(a**2)



[2. 4. 6. 8.]
[ 4.  6.  8. 10.]
[ 4.  8. 12. 16.]
[ 4. 16. 36. 64.]


In [47]:
myarr = np.zeros([2,3])
print ("Array of zeros: \n\n" , myarr)

myarr1 = np.ones([2,3])
print ("Array of ones: \n\n" , myarr1)

myarr3 = np.full([2,3] , 5) # full array with 5
print ("Array of full: \n\n" , myarr3)

myarr2 = np.arange(1,10,2) # start , stop , step
print("Array of range: \n\n" , myarr2)


print("\n" , np.linspace(1,10,5)) # start , stop , number of elements // linspace is used to create an array of evenly spaced numbers over a specified interval.

Array of zeros: 

 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones: 

 [[1. 1. 1.]
 [1. 1. 1.]]
Array of full: 

 [[5 5 5]
 [5 5 5]]
Array of range: 

 [1 3 5 7 9]

 [ 1.    3.25  5.5   7.75 10.  ]


In [48]:
# average of the array

arr = np.array([1,2,3,4,5])
print("Average of the array: " , np.mean(arr))

Average of the array:  3.0


In [57]:
# random numbers

ar = np.random.rand(3,2) # 3 rows and 2 columns
print("\nRandom numbers: \n\n" , ar)
print("\nMaximum value in the array: \n\n" , np.max(ar))
print("\nMinimum value in the array: \n\n" , np.min(ar))
print("\nSum of the array: \n\n" , np.sum(ar))
print("\nAverage of the array:\n\n " , np.mean(ar))

ar2 =np.array([5,6,9,8,4])
print("\n" ,ar2.max())
print("\n",ar2.min())
print("\n" ,ar2.sum())
print("\n" ,ar2.mean())

print("\n Identitiy Matrix\n : ")

ar3 = np.eye(3) # identity matrix
print(ar3)


Random numbers: 

 [[0.93737449 0.85292393]
 [0.85825819 0.86941096]
 [0.08311549 0.63755062]]

Maximum value in the array: 

 0.9373744913984289

Minimum value in the array: 

 0.08311549259845252

Sum of the array: 

 4.238633675351739

Average of the array:

  0.7064389458919565

 9

 4

 32

 6.4

 Identitiy Matrix
 : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
# absolute value : give positve value
array =  [2,5,7,8,9]

print(np.abs(array)) # absolute value
print("\n" , np.sqrt(array)) # square root
print("\n" , np.square(array)) # square
print("\n" , np.log(array)) # logarithm

[2 5 7 8 9]

 [1.41421356 2.23606798 2.64575131 2.82842712 3.        ]

 [ 4 25 49 64 81]

 [0.69314718 1.60943791 1.94591015 2.07944154 2.19722458]


In [ ]:
# what is array in numpy:
#  array is a collection of homogeneous item.

# list : collection of heterogeneous items.

# for numpy we used list to create an array but the list should be homogeneous.
